### ISSUE TITLE
ModuleNotFoundError: No module named 'wrapped_module_0'

### ISSUE THREAD

**Issue by firas1925** [pylbm/pylbm#176] opened 2023-10-07 12:18 UTC
Hi
I am reaching out to you regarding an issue I encountered while trying to execute the Poiseuille flow example using PyLBM. The example is available at this link: https://pylbm.readthedocs.io/en/latest/notebooks/05_Poiseuille.html.

ModuleNotFoundError: No module named 'wrapped_module_0'

More Details:

CalledProcessError                        Traceback (most recent call last)
File ~\Desktop\jupyter\pylbm\generator\autowrap.py:81, in CodeWrapper._process_files(self, routine)
     80 try:
---> 81     retoutput = check_output(command, stderr=STDOUT)
     82 except CalledProcessError as e:

File c:\users\lenovo\appdata\local\programs\python\python38\lib\subprocess.py:415, in check_output(timeout, *popenargs, **kwargs)
    413     kwargs['input'] = empty
--> 415 return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    416            **kwargs).stdout

File c:\users\lenovo\appdata\local\programs\python\python38\lib\subprocess.py:516, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    515     if check and retcode:
--> 516         raise CalledProcessError(retcode, process.args,
    517                                  output=stdout, stderr=stderr)
    518 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['c:\\users\\lenovo\\appdata\\local\\programs\\python\\python38\\python.exe', 'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\tmpd9wslaf8_sympy_compile\\build.py']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

CodeWrapError                             Traceback (most recent call last)
Cell In[2], line 146
    144 dx = 1.0 / 128
    145 Tf = 20
--> 146 run(dx, Tf)

Cell In[2], line 107, in run(dx, Tf, generator, sorder, with_plot)
     59 qxy = dummy * qx * qy
     61 dico = {
     62     "box": {"x": [xmin, xmax], "y": [ymin, ymax], "label": [2, 1, 0, 0]},
     63     "space_step": dx,
   (...)
    104     "generator": generator,
    105 }
--> 107 sol = pylbm.Simulation(dico, sorder=sorder)
    109 if with_plot:
    110     # init viewer
    111     viewer = pylbm.viewer.matplotlib_viewer

File ~\Desktop\jupyter\pylbm\simulation.py:142, in Simulation.__init__(self, dico, sorder, dtype, check_inverse, initialize)
    139     method.set_iload()
    140     method.generate(self.container.sorder)
--> 142 self.generator.compile()
    144 self.init_type = dico.get('inittype', 'moments')
    145 self.init_data = dico.get('init', None)

File ~\Desktop\jupyter\pylbm\generator\generator.py:26, in Generator.compile(self)
     25 def compile(self):
---> 26     self.module = autowrap(self.routines.values(),
     27                            self.backend,
     28                            self.directory,
     29                            generate=self.generate,
     30                            verbose=self.verbose)

File ~\Desktop\jupyter\pylbm\generator\autowrap.py:156, in autowrap(routines, backend, tempdir, generate, args, flags, verbose)
    153 CodeWrapperClass = get_code_wrapper(backend)
    154 code_wrapper = CodeWrapperClass(code_generator, tempdir, flags, generate, verbose)
--> 156 return code_wrapper.wrap_code(routines)

File ~\Desktop\jupyter\pylbm\generator\autowrap.py:59, in CodeWrapper.wrap_code(self, routines)
     57     self._prepare_files(routines)
     58     self._generate_code(routines)
---> 59     self._process_files(routines)
     60 if self.module_name in sys.modules:
     61     sys.modules.pop(self.module_name)

File ~\Desktop\jupyter\pylbm\generator\autowrap.py:83, in CodeWrapper._process_files(self, routine)
     81     retoutput = check_output(command, stderr=STDOUT)
     82 except CalledProcessError as e:
---> 83     raise CodeWrapError(
     84         "Error while executing command: %s. Command output is:\n%s" % (
     85             " ".join(command), e.output.decode()))
     86 if self.verbose:
     87     print(retoutput)

CodeWrapError: Error while executing command: c:\users\lenovo\appdata\local\programs\python\python38\python.exe C:\Users\LENOVO\AppData\Local\Temp\tmpd9wslaf8_sympy_compile\build.py. Command output is:
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Temp\tmpd9wslaf8_sympy_compile\build.py", line 4, in <module>
    import wrapped_module_0
ModuleNotFoundError: No module named 'wrapped_module_0'

**Comment by pcHanYang** [comment] 2024-02-01 16:32
Hi, I am experiencing the same error on windows platform. Tried conda and wsl. Getting same error.

**Comment by gouarin** [comment] 2024-02-02 13:12
This error is probably because you don't have a C compiler installed on your system. What you can do, it's to change the generator to NumPy into the simulation dictionary. You just have to add an entry such as

```
"generator": "numpy",
```

If it works, then I encourage you to install a C compiler on your windows by following this link
https://learn.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2022

**Comment by pcHanYang** [comment] 2024-02-02 16:17
> This error is probably because you don't have a C compiler installed on your system. What you can do, it's to change the generator to NumPy into the simulation dictionary. You just have to add an entry such as
> 
> ```
> "generator": "numpy",
> ```
> 
> If it works, then I encourage you to install a C compiler on your windows by following this link https://learn.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2022
> 
> To be able to use the Cython generator and have better performance.

Thank you for the reply. I switched the 'generator' to 'numpy', and it works. :) However, I still cannot get cython generator working. I tried visual studio and msys2. g++ compiler installed fine but still getting the same error. I also tried ubuntu with wsl, installed pylbm in conda environment, still no luck. :(

**Comment by gouarin** [comment] 2024-02-02 17:12
Do you have installed `c-compiler`in the conda environment ? 
Could you try a Cython example to see if Cython works properly ?

**Comment by pcHanYang** [comment] 2024-02-03 02:54
Is c-compiler a package? I couldn't find it in conda's default channel.
Yes. I tried Cython 'helloworld' examples in both windows conda and wsl ubuntu conda environments and all works fine.

**Comment by gouarin** [comment] 2024-02-03 06:18
I can reproduce it on my laptop with a new environment. It seems that pylbm is broken with cython 3.x.x.
If you install cython=0.29, it should work. (Note: the python version must be <3.12).

I will make a fix in the next few days.

**Comment by gouarin** [comment] 2024-02-03 06:20
And `c-compiler`is on `conda-forge` : https://anaconda.org/conda-forge/c-compiler
But it's probably not necessary.

**Comment by gouarin** [comment] 2024-02-13 09:10
This issue is fixed in https://github.com/pylbm/pylbm/pull/180

**Closed by gouarin** 2024-02-13 09:10 UTC
